- .travis.yml
- Dockerfile.test
- Makefile
- release_bot/release_bot.py
- tests/src/example.spec
- tests/src/example_updated.spec
- tests/src/example_updated_changelog.spec
- tests/test_fedora.py
- tests/test_load_release_conf.py
- tests/test_pypi_2.py
- tests/test_pypi_3.py
- tests/test_specfile.py
This fixes #23 as it adds tests for Fedora and also a Dockerfile for testing in Fedora environment in Travis. It also changes the structure of Fedora-related functionality, mainly it was rewritten into more functions to provide the ability to mock them.
> Fedora tests

- .s2i/bin/assemble
- .s2i/bin/run
- Dockerfile
- Dockerfile.dev
- README.md
- release_bot/release_bot.py
- tests/test_fedora.py
- tests/test_load_release_conf.py
This would fix #24 as it add support for keytab so Fedora releasing would be possible in Docker image and in OpenShift.
> Fedora releasing

- release_bot/github.py
- release_bot/releasebot.py
Previously we found a merged PR matching the latest PyPi release
and then found a newer merged PR and tried to do a github/pypi/fedora release
of that version. If that PR was for some reason wrong, the bot
would crash loop on that PR forever.
With this change we simply find the newest merged release PR
and try to do a github/pypi/fedora release of that version.
Even if the PR is bad, the bot returns to the Light side of the Force
once the maintainer creates newer (correct) PR.
Fixes #45
> Iterate over PRs in desc order

- tests/test_fedora.py
fedpkg repo HEAD seems to not be rpmlint compliant, which results in:
```
fedpkg.spec: E: specfile-error sh: line 0: fg: no job control
fedpkg.spec: E: specfile-error sh: line 0: fg: no job control
0 packages and 1 specfiles checked; 2 errors, 0 warnings.
```
Strangely this occurs only in a container.
> Fix TestFedora:test_lint() by cloning zip instead of fedpkg

- .pylintrc
- README.md
- release_bot/configuration.py
- release_bot/exceptions.py
- release_bot/git.py
- release_bot/github.py
- release_bot/releasebot.py
- release_bot/utils.py
- tests/test_load_release_conf.py
This PR adds the ability for bot to be triggered by github issue with name like 'x.x.x release'. If this issue is made by someone who has commit access to repository, bot does the following:
- checks if  new version > current version
- clones the repo
- creates a new branch named x.x.x-release
- edits CHANGELOG.md with log from parsed `git log` excluding merges
- The expected workflow is that this will provide maintainer with something to base their changelog on
- Tries to find `__version__` variable in files like `__init__.py`, `setup.py`,` version.py` and update it to the new version number
- Pushes it's changes and makes a PR from the new branch with changes summed up
- if PR is made, closes the original issue and comments a link to the PR
If this PR is merged (further edits are …
> Add ability to make PRs with version change based on release issue

- release_bot/releasebot.py
When a release issue has a whitespace around the version string the version validation does not work. This PR fixes the problem and adds some warnings so we know what's going on next time.
> Make issue version validation work

- Jenkinsfile
Jenkins file tested in this job:
https://ci.centos.org/job/release-bot/30/console
Some tests are still skipped. I contacted centos-ci guys with question how to work with secrets, but it seems that user-scoped credentials are not supported by jenkins yet. See [this stackoverflow question](https://stackoverflow.com/questions/48281806/how-can-i-get-user-scoped-credentials-personal-credentials-in-withcredentials) for more information.
This command is used for running tests instead of `make test-in-container`
```
docker run -v /root:/usr/src/app:Z -e GITHUB_USER= -e GITHUB_TOKEN= release-bot-tests make test TEST_TARGET=tests/$test_target
```
just because there is no support for `-it` options. We can leave it like this or change the Makefile.
> Jenkins pipeline with tests running in parallel

- README.md
Related #152 #33 
I started with the default approach creating new releases using pull requests. I can add documentation how to create releases with `trigger_on_issue` option in follow-up PR, if needed.
> Document how to try release-bot locally

- tests/github_utils.py
- tests/test_bot.py
- tests/test_github.py
If the API is down, let's just fail the tests and wait for it to be up again.
Also, the status.github.com does not work any more.
> remove check for github_api_status

- release_bot/github.py
- release_bot/releasebot.py
This solves the bug #173 
* make_new_pypi_release() will now check back to master hence will have no side effect to other functions.
* make_release_pr() will additionally checkout for master again because its important that the current branch is master before release pr branching
* make_release_pr() will also check back to master after doing the release_pr
> Make function checkout back to master

- .s2i-dev/bin/assemble
- .s2i/bin/assemble
According to merged PR #165, there is no longer a need for check PyPi configuration file. This is a fix for  `ERROR: no PyPi configuration found` produced by s2i when `.pypirc` is not found.
> delete s2i check for pypi configuration

- .gitignore
- README.md
- release_bot/configuration.py
- release_bot/releasebot.py
- tests/src/conf_with_clone_url.yaml
- tests/src/sample_conf.yaml
- tests/test_bot.py
- tests/test_load_local_conf.py
Added configuration option `clone_url`,  that
allows the user to explicitly specify the URL of the
repository to be cloned.
Fixes #179
> Add new configuration option to specify clone url.

- Dockerfile
- Dockerfile.dev
- openshift-template-dev.yml
- openshift-template.yml
- release_bot/configuration.py
- release_bot/releasebot.py
- release_bot/webhooks.py
- requirements.txt
- tests/test_webhooks.py
Implementation of Github callbacks related to  #112. 
As a quite new contributor I was thinking about more solutions for this feature, just tell me if there are possible improvements. This also could be integrated with #119 as github callbacks contains information about repository.  
Possible user workflow for this feature:
1. Deploy release-bot on Openshift online with openshift-template.yml
2. Set webhook to user's repo watched by release-bot.  
3. Add `webhook_hanlder: true` into `conf.yaml`
These steps should be added to README.md more specifically.
> implementation of Github webhooks handling

- openshift-template-dev.yml
It will be more straightforward if there is DockerHub repository in a variable within
openshift-template-dev.yml. I was stuck on this when I was working with my own container for the first time. "Production" template should stay without change. 
If you like this little change please marge it.
> In openshift-template-dev add container repository into variable.

- release_bot/cli.py
- release_bot/configuration.py
- release_bot/github.py
- release_bot/pypi.py
- release_bot/releasebot.py
- tests/test_bot.py
- tests/test_github.py
It can be triggered by the argument `-n` or `--dryrun`.
I have not changed the info messages which are printed out. I have just skipped all the remote operations (which can cause a change, like commenting, adding a tag to the issue, making a PR). The reason behind this was mainly to simulate the run through of the release-bot, instead of making any remote change.
Solves #171
> Added the dry-run functionality.

- release_bot/utils.py
Solves #212 .
I also edited the regex so that it only matches when the word "release" is at the end of the issue title. For example: 
1. `new major release` will be matched
2. `0.1.1 release` will be matched
3. `let's release a version` will **NOT** be matched. (in the previous case, this would have been matched as well)
> Fixed empty warnings when the bot is unable to parse out the version.

- release_bot/configuration.py
- release_bot/github.py
- release_bot/pypi.py
- release_bot/releasebot.py
- release_bot/utils.py
- tests/test_github.py
- tests/test_load_release_conf.py
- tests/test_utils.py
Previously `get_pypi_project_from_setup_cfg()` aways returned `None`
because we had not fetched the `setup.cfg` before calling it.
> Make getting pypi project from setup.cfg work

- README.md
- gitchangelog/.gitchangelog.rc
- gitchangelog/markdown.tpl
- release_bot/cli.py
- release_bot/configuration.py
- release_bot/git.py
- release_bot/github.py
- release_bot/init_repo.py
- release_bot/releasebot.py
- requirements.txt
This PR is still incomplete!
Solves #91  
To test this, copy gitchangelog/.gitchangelog.rc and gitchangelog/markdown.tpl into the the root dir of the project. 
I need some help from maintainers regarding the following points to complete this pr:
* How should I include the the not python files (.gitchangelog.rc and template.tpl) into the package and automatically copy it using python to the repo. (This would help in solving #168 also)
* How should the change log look like by default? This would help me create the template for the gitchangelog and also currently the changelogs are divided into parts[(New, Changes, Fix, Others)](https://github.com/vaab/gitchangelog/edit/master/README.rst#L141-L176) Do we need that?
sidenote: I have also included the commits from my previous …
> GitReleaseLog

- release_bot/github.py
- release_bot/init_repo.py
- release_bot/releasebot.py
As discussed [here](https://github.com/user-cont/release-bot/pull/226#issuecomment-496225678).
There's one commit which fixes a docstring in github.py as well.
So far, this PR includes:
1. Handling an exception when an incorrect value is given to the refresh_interval parameter. 
2. Shows warnings for incorrectly set git credentials (email and username). 
3. Prints a message when the operation is interrupted by the user, instead of printing the whole stacktrace.
I was unsure on how to format the messages. It can be discussed upon, if required.
> Handling exceptions in init phase.

- release_bot/configuration.py
- release_bot/github.py
- release_bot/new_release.py
- release_bot/releasebot.py
- release_bot/webhooks.py
- requirements.txt
- tests/test_bot.py
- tests/test_github.py
Commenting on Issues and PRs are available for Github but also Pagure since now. I added two new variables into the private config file `pagure_token` and `pagure_username`. I'm just thinking if we should add this into README or wait till all Github features will be implemented also for Pagure.
Ogr doesn't have released commenting on issues yet. If you want to try locally you must install ogr from Github, not from requirements.txt
`pip install git+https://github.com/packit-service/ogr@master`
> commenting on Issues/PRs with ogr

- release_bot/configuration.py
- release_bot/github.py
- release_bot/releasebot.py
- tests/test_bot.py
- tests/test_github.py
Related to #190, #193, but still not fully implement these issues.
I replaced Github API with ogr for closing and checking Issues.
Integration tests are passing for Github, unit tests are provided in ogr. I still need to add several features into ogr to fully support Pagure, then I can write tests for Pagure too.
> closing issues using ogr

- release_bot/github.py
- tests/test_github.py
- tests/unit/test_github.py
Function `latest_release` inside `github.py` is returning the latest project release number. Now the body of this function is replaced from Github API call with ogr.
> replace latest_release function's body with ogr

- files/install-rpm-packages.yaml
- requirements.txt
- setup.cfg
and avoid DeprecationWarnings (in 0.9.0)
> Temporary lock ogr to 0.8.0 to make tests pass
