user-cont/release-bot

bot.py, conf.yaml
Introduces releasing to Fedora dist-git. Also, some code structure improvements.
=> Feature fedora releasing

Makefile, release_bot.py, requirements.txt, tests/src/example.spec, tests/src/example_updated.spec, tests/src/example_updated_changelog.spec, tests/test_changelog.py, tests/test_specfile.py
=> Add some basic tests

Makefile, release_bot/release_bot.py, requirements.txt, tests/src/rlsbot-test/rlsbot_test.py, tests/src/rlsbot-test/setup.py, tests/test_pypi_2.py, tests/test_pypi_3.py
=> Add Pypi tests

release_bot/release_bot.py
=> Drop shell=True

release_bot/release_bot.py, tests/test_fedora.py, tests/test_load_release_conf.py, tests/test_pypi_2.py, tests/test_pypi_3.py, tests/test_specfile.py
=> Commits to hopefuly improve readability of the code

.s2i-dev/bin/run, .s2i/bin/assemble, .s2i/bin/run, Dockerfile, Dockerfile.dev
=> Use nss_wrapper to create/use custom passwd file 

release_bot/configuration.py, release_bot/releasebot.py
Reported by https://pypi.org/project/bandit
=> Bandit fixes

release_bot/exceptions.py, release_bot/fedora.py, release_bot/github.py, release_bot/pypi.py, release_bot/releasebot.py, release_bot/utils.py, tests/test_fedora.py, tests/test_pypi_2.py, tests/test_pypi_3.py, tests/test_specfile.py
=> Add status comments to Github PR

release_bot/configuration.py
Fixes:
```
File "/opt/app-root/src/.local/lib/python3.6/site-packages/release_bot/configuration.py", line 125, in load_release_conf
if parsed_conf['fedora'] and not self.fas_username:
KeyError: 'fedora'
```
=> Fix a KeyError

.s2i-dev/bin/run, .s2i/bin/run
=> [.s2i/bin/run] Don't use --keytab if there's no such file

.bandit, .pylintrc
- Use bandit/pylintrc file from kwaciaren.
-----
Please, do not change .bandit/.pylintrc files here, but first in [our config repo](https://github.com/user-cont/kwaciaren) so we can share common configuration between all projects.
(Kwaciaren, the config repo, has scripts for sharing such files.)
=> Use config from user-cont/kwaciaren

release_bot/releasebot.py
=> Add collaborator to the list of authorized users

release_bot/fedora.py, release_bot/git.py, release_bot/pypi.py, release_bot/utils.py, tests/test_fedora.py
=> rename shell_command to run_command

release_bot/github.py, release_bot/releasebot.py
=> Check latest github release before trying to create new

Dockerfile, Dockerfile.dev, Dockerfile.test, README.md, release_bot/configuration.py, release_bot/github.py, release_bot/pypi.py, requirements.txt
https://github.com/TomasTomecek/ansible-bender/issues/12
https://github.com/TomasTomecek/ansible-bender/pull/13
=> add a way to authenticate as a github app

README.md, hack/clean-testing-github-repos, tests/github_utils.py
=> testing: add a way to clean test repos

hack/clean-testing-github-repos, release_bot/git.py, release_bot/releasebot.py, tests/github_utils.py, tests/test_bot.py, tests/test_github.py
```
=== 57 passed in 188.77 seconds ===
```
=> This time!

release_bot/configuration.py, release_bot/github.py, release_bot/releasebot.py, tests/conftest.py, tests/github_utils.py, tests/test_bot.py, tests/test_github.py, tests/unit/test_github.py
=> fix: latest_release() returns dict now

release_bot/git.py, release_bot/releasebot.py
* log when the git repo is being cleaned up
* bot/run: pull && work && repeat; clean once done
=> Pull new content in the endless loop

release_bot/releasebot.py
https://travis-ci.org/user-cont/release-bot/builds/494882934
=> Fix a bug introduced in #147

release_bot/releasebot.py
Moved GitHub issue trigger to another try-except block.
=> Fixed a bug introduced in #162

README.md, release_bot/releasebot.py, release_bot/utils.py, tests/test_utils.py
rebased and cherrypicked into a fresh branch
=> SemVer Version format support

README.md, release-conf-example.yaml, release_bot/configuration.py, release_bot/releasebot.py, tests/test_bot.py
I have made the changes as we discussed on #162
=> Added condition to check if the user wants to release on PyPi.

Jenkinsfile, Makefile
Removed the `GITHUB_USER` env variable from the Makefile
and the Jenkinsfile
=> Remove GITHUB_USER env variable

release_bot/github.py, tests/unit/test_github.py
=> Check tag_name instead of release_name

README.md
Updated README.
Added AUR installation guidelines.
=> Added release-bot to the Arch User Repository.

tests/test_bot.py
Forgot to update the tests in the previous PR (#192 ), which were causing the tests to fail.
=> Updated tests.

tests/test_bot.py
- Fix test failures due to the new classes.
- Updated `test_bot.py`.
=> Fixed test failures.

release_bot/utils.py, tests/test_utils.py
Referencing issue #129
What do you guys think, would this fix the issue?
Also, I'm not sure whether to include the setup.cfg as well
=> Add support for using the version variable

release_bot/utils.py, tests/test_bot.py, tests/test_load_local_conf.py, tests/test_load_release_conf.py
```
=== 45 passed in 168.18 seconds ===
```
=> All tests now pass locally

CHANGELOG.md, README.md
At the moment you can't see all the changes under the newest release. I also changed incorrectly tagged users.
=> fix changelog

release_bot/configuration.py
=> Perform operations on pypi_project only when pypi is True.

README.md, release_bot/configuration.py, release_bot/git.py, release_bot/github.py, release_bot/init_repo.py, release_bot/releasebot.py, tests/src/conf_with_gitchangelog.yaml, tests/test_load_local_conf.py
All tests passed locally.
Edit: Fixes #223
=> Get gitchangelog option from conf not release-conf

release_bot/init_repo.py
=> Stripped author_name and author_email fields in init.

release_bot/github.py, release_bot/releasebot.py, release_bot/utils.py, release_bot/webhooks.py, tests/test_bot.py
(No need for new tests since I replaced just bodies of functions which already have tests.)
=> create PRs using ogr

release_bot/git.py, release_bot/github.py, release_bot/releasebot.py
Create a release from PR using ogr. Parsing changelog and add its body into new release as a description is consistent with the previous version.
=> make releases using ogr

release_bot/github.py, tests/test_github.py
After merging this PR we can finally close #190. This also allows us to debug release-bot on Pagure (#193) and I started work on it. Since now it should be trivial to add also support for Gitlab when the functionality will be added to Ogr-lib.
=> replace last API calls with ogr

tests/unit/test_github.py
- Release mocking is out of date.
=> Fix mocking of the GithubRelease.

release_bot/utils.py, tests/test_utils.py
Fixes #243
Signed-off-by: Marek Cermak <macermak@redhat.com>
modified:   release_bot/utils.py
modified:   tests/test_utils.py
=> Add __about__ to version files

setup.py, test-requirements.txt
Signed-off-by: Marek Cermak <macermak@redhat.com>
modified:   setup.py
new file:   test-requirements.txt
=> Add test requirements

release_bot/init_repo.py, release_bot/releasebot.py, tests/requirements.txt, tests/test_bot.py
Signed-off-by: Marek Cermak <macermak@redhat.com>
modified:   release_bot/init_repo.py
modified:   release_bot/releasebot.py
modified:   tests/requirements.txt
modified:   tests/test_bot.py
=> Run once when refresh_interval is not provided

release_bot/pypi.py, release_bot/releasebot.py
=> rm dist/ before creating tar & wheel

README.md, release_bot/configuration.py, release_bot/init_repo.py, release_bot/releasebot.py
=> refresh_interval related changes

Dockerfile.app, Makefile, README.md, files/install-rpm-packages.yaml, release-conf.yaml, release_bot/configuration.py, tests/test_bot.py, tests/test_github.py, tests/test_load_release_conf.py
Also: fix issues in `Makefile` & `Dockerfile.app`
=> Trigger_on_issue on by default

release_bot/__init__.py, release_bot/celery_task.py, release_bot/cli.py, release_bot/git.py, release_bot/init_repo.py, release_bot/new_pr.py, tests/test_bot.py, tests/test_github.py, tests/test_load_local_conf.py, tests/test_webhooks.py
Improved PEP8 Compatibility of the codebase.
=> Improve PEP8 Compatibilty

README.md
=> Fix typo in Readme file

release_bot/utils.py
Fixes issue [[BUG] Version update is not aborted with multiple files](https://github.com/user-cont/release-bot/issues/245),
according to the discussion by @CermakM and @jpopelka. :)
=> Fixes issue #245
